<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131002001610 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE timkandel_plugin_packagistfe_domain_model_package_version DROP FOREIGN KEY FK_63086BCEDE686795");
		$this->addSql("CREATE TABLE timkandel_packagistfe_domain_model_package (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(80) NOT NULL, description VARCHAR(255) NOT NULL, time DATETIME NOT NULL, maintainer VARCHAR(80) NOT NULL, type VARCHAR(80) NOT NULL, totaldownloads INT NOT NULL, monthlydownloads INT NOT NULL, dailydownloads INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE timkandel_packagistfe_domain_model_package_version (persistence_object_identifier VARCHAR(40) NOT NULL, package VARCHAR(40) DEFAULT NULL, version VARCHAR(255) NOT NULL, time DATETIME NOT NULL, INDEX IDX_37A5361CDE686795 (package), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE timkandel_packagistfe_domain_model_package_version ADD CONSTRAINT FK_37A5361CDE686795 FOREIGN KEY (package) REFERENCES timkandel_packagistfe_domain_model_package (persistence_object_identifier)");
		$this->addSql("DROP TABLE timkandel_plugin_packagistfe_domain_model_package");
		$this->addSql("DROP TABLE timkandel_plugin_packagistfe_domain_model_package_version");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE timkandel_packagistfe_domain_model_package_version DROP FOREIGN KEY FK_37A5361CDE686795");
		$this->addSql("CREATE TABLE timkandel_plugin_packagistfe_domain_model_package (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(80) NOT NULL, description VARCHAR(255) NOT NULL, time DATETIME NOT NULL, maintainer VARCHAR(80) NOT NULL, type VARCHAR(80) NOT NULL, totaldownloads INT NOT NULL, monthlydownloads INT NOT NULL, dailydownloads INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE timkandel_plugin_packagistfe_domain_model_package_version (persistence_object_identifier VARCHAR(40) NOT NULL, package VARCHAR(40) DEFAULT NULL, version VARCHAR(255) NOT NULL, time DATETIME NOT NULL, INDEX IDX_63086BCEDE686795 (package), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE timkandel_plugin_packagistfe_domain_model_package_version ADD CONSTRAINT FK_63086BCEDE686795 FOREIGN KEY (package) REFERENCES timkandel_plugin_packagistfe_domain_model_package (persistence_object_identifier)");
		$this->addSql("DROP TABLE timkandel_packagistfe_domain_model_package");
		$this->addSql("DROP TABLE timkandel_packagistfe_domain_model_package_version");
	}
}

?>